// Test for Sprint 13:

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzgxYWU3MDcxYmIyZTE4ZjYwOTRiZGIiLCJpYXQiOjE3MzY2MzE5NTMsImV4cCI6MTczNzIzNjc1M30.Z9zV42FZZsKwh4ZSYyFu2qX7sLsqII_3Od8lsaWjvuM
@token2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzgyZTg1NjcyMDU5OTY4ZWYzODdhN2UiLCJpYXQiOjE3MzY2MzI0MzYsImV4cCI6MTczNzIzNzIzNn0.MZrdW67VK0DVyPHhf6lS2LcXDozZGta6QYraUS5-uSQ
###

POST http://localhost:3001/signin HTTP/1.1
content-type: application/json

{
    "email": "TTC@gmail.com",
    "password": "Itsjustme"
}


###

POST http://localhost:3001/signup HTTP/1.1
content-type: application/json

{
    "email": "TTC@gmail.com",
    "password": "Itsjustme",
    "name": "Thursaun",
    "avatar": "https://example.com/me"
}


###

GET http://localhost:3001/users/me HTTP/1.1
Authorization: Bearer {{token}}

###

PATCH  http://localhost:3001/users/me HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "name": "Jessica Vanessa - The scammer",
    "avatar": "https://example.com/scam"
}

###


POST http://localhost:3001/items HTTP/1.1
Authorization: Bearer {{token2}}
content-type: application/json

{
  "name": "Winter Jacket",
  "weather": "cold",
  "imageUrl": "https://example.com/winter-jacket.jpg"
}

###

DELETE  http://localhost:3001/items/6782ead21264c78c779a51dd HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

###


// Test for Sprint 12:


GET http://localhost:3001/users/me HTTP/1.1

###


GET http://localhost:3001/users/6780473a86ae15c067f8584b  HTTP/1.1

###

POST http://localhost:3001/users HTTP/1.1
content-type: application/json

{
  "name": "Jessica Vanessa",
  "avatar": "https://example.com/pops",
  "email": "HarryPotter@gmail.com",
  "password": "HedwigForever",
}

###

POST http://localhost:3001/items HTTP/1.1

content-type: application/json

{
  "name": "Winter Jacket",
  "weather": "cold",
  "imageUrl": "https://example.com/winter-jacket.jpg"
}

###


PUT http://localhost:3001/items/67803d3186ae15c067f85840/likes  HTTP/1.1
content-type: application/json

{
  "name": "Winter Jacket",
  "weather": "cold",
  "imageUrl": "https://example.com/winter-jacket.jpg"
}