
POST http://localhost:3001/signup HTTP/1.1
content-type: application/json

{
  "email": "HarryPotter11@gmail.com",
  "password": "HedwigForever11",
  "name": "Jessica Vanessa",
  "avatar": "https://example.com/babe",
}


###

POST http://localhost:3001/signin HTTP/1.1

{
  "email": "HarryPotter@gmail.com",
  "password": "HedwigForever",
}


###

POST http://localhost:3001/signup HTTP/1.1
content-type: application/json

{
    "email": "HarryPotter11@gmail.com",
    "password": "HedwigRIP11",
    "name": "Jessica Vanessa - The scammer",
    "avatar": "https://example.com/babe"
}


###

GET http://localhost:3001/items HTTP/1.1

###

GET http://localhost:3001/users/me HTTP/1.1

###


GET http://localhost:3001/users/6780473a86ae15c067f8584b  HTTP/1.1

###

POST http://localhost:3001/users HTTP/1.1
content-type: application/json

{
  "name": "Jessica Vanessa",
  "avatar": "https://example.com/pops",
  "email": "HarryPotter@gmail.com",
  "password": "HedwigForever",
}

###

POST http://localhost:3001/items HTTP/1.1
content-type: application/json

{
  "name": "W",
  "weather": "cold",
  "imageUrl": "https://example.com/winter-jacket.jpg"
}

###


PUT http://localhost:3001/items/67803d3186ae15c067f85840/likes  HTTP/1.1
content-type: application/json

{
  "name": "Winter Jacket",
  "weather": "cold",
  "imageUrl": "https://example.com/winter-jacket.jpg"
}